question_data = {
    "response_code": 0,
    "results": [
        {
            "type": "multiple",
            "difficulty": "hard",
            "category": "Entertainment: Books",
            "question": "In the book &quot;The Martian&quot;, how long was Mark Watney trapped on Mars (in Sols)?",
            "correct_answer": "549 Days",
            "incorrect_answers": ["765 Days", "401 Days", "324 Days"]
        },
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In Need For Speed: Most Wanted (2005), how many people are there to defeat on the blacklist?",
         "correct_answer": "15", "incorrect_answers": ["5", "10", "20"]},
        {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature",
         "question": "What is the largest living organism currently known to man?", "correct_answer": "Honey Fungus",
         "incorrect_answers": ["Blue Whale", "Redwood Tree", "The Coral Reef"]},
        {"type": "boolean", "difficulty": "hard", "category": "History",
         "question": "Japan was part of the Allied Powers during World War I.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "multiple", "difficulty": "easy", "category": "Sports",
         "question": "Which country hosted the 2022 FIFA World Cup?",
         "correct_answer": "Qatar",
         "incorrect_answers": ["USA", "Japan", "Switzerland"]},
        {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Television",
         "question": "In Two and a Half Men, what is Alan Harper&#039;s son&#039;s name?", "correct_answer": "Jake",
         "incorrect_answers": ["John", "Jeremy", "James"]},
        {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
         "question": "Which &quot;Toy Story&quot; character was voiced by Don Rickles?",
         "correct_answer": "Mr. Potato Head", "incorrect_answers": ["Slinky Dog", "Hamm", "Rex"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "multiple", "difficulty": "medium", "category": "Art",
         "question": "Which of these are the name of a famous marker brand?", "correct_answer": "Copic",
         "incorrect_answers": ["Dopix", "Cofix", "Marx"]},
        {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
         "question": "Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?",
         "correct_answer": "Cabbage Patch Kids",
         "incorrect_answers": ["Transformers", "Care Bears", "Rubik&rsquo;s Cube"]}]}
